name: Restrict PR Targets

on:
  pull_request:
    types: [opened, edited]

jobs:
  check-target-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Check if target branch is allowed
        run: |
          TARGET_BRANCH=${{ github.event.pull_request.base.ref }}
          SOURCE_BRANCH=${{ github.event.pull_request.head.ref }}

          if [[ "$TARGET_BRANCH" == "main" ]]; then
            if [[ "$SOURCE_BRANCH" != "develop" && ! "$SOURCE_BRANCH" =~ ^hotfix/ ]]; then
              echo "Error: You can only merge to 'main' from 'develop' or 'hotfix/*' branches."
              exit 1
            fi
          fi
          echo "PR target and source branches are valid."
